### ISSUE TITLE
Convert to string

### ISSUE THREAD

**Issue by Un3qual** [diegohaz/styled-theme#23]
Is there a way to convert a `palette()` to a string for use with `styled-components/polished`?

**Comment by diegohaz** [comment]
`palette()` returns a function that accepts `props` from `styled-components`, which, finally, returns a string. Then I think you will need to call that like `palette()()`.

**Comment by ng-hai** [comment]
`palette()()` return wrong color.

In my defined theme, there is a grayscale palette that has the first color is `rgba(0, 0, 0, 0.2)`.
When using in Storybook, it always returns `#212121`

```javascript
const boxShadow = ({ shadow }) => {
  console.log(palette('grayscale', 0)()) // ==> #212121
  return shadow ? `0px 0px 6px ${palette('grayscale', 0)()}` : 'none'
}
```

**Comment by diegohaz** [comment]
@ng-hai You don't need to call `palette()()`. Just use `palette()`:
```js
const boxShadow = ({ shadow }) => {
  return shadow ? `0px 0px 6px ${palette('grayscale', 0)}` : 'none'
}
```

**Comment by diegohaz** [comment]
Another way to use it with `polished` is through [`styled-tools`](https://github.com/diegohaz/styled-tools)'s `call` method.

**Comment by ng-hai** [comment]
@diegohaz I don't know why using `0px 0px 6px ${palette('grayscale', 0)}` the `box-shadow` property doesn't render. That's why I have to use `palette()()`

**Comment by diegohaz** [comment]
@ng-hai Could you console.log your component's props?

**Comment by ng-hai** [comment]
Here are its props when I use with `styled-components`

```javascript
box-shadow: ${ifProp('shadow', `0px 0px 6px ${palette('grayscale', 0)}`, 'none')};`
```

![image](https://user-images.githubusercontent.com/19520278/35203076-e672a66e-ff58-11e7-95dc-89db811885ec.png)

And here is the Button's styles in the DOM

![image](https://user-images.githubusercontent.com/19520278/35203146-664ea1c6-ff59-11e7-9692-36e59487f54d.png)
